### ISSUE TITLE
Polls not working/showing 

### ISSUE THREAD

**Issue by mmOrthosoftHM** [Jefferson49/joomla4_plugin_sexy_polling#102]
Hello, today i installed Sexy Polling for my Homepage. After i created a Poll in the backend with answers, i inserted "[sexypolling id="4"]" in the frontend but the problem is that nothing is showing up. 
Thank you in advance.

![Screenshot 2024-06-19 105117](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/173246323/1ca83dff-8ada-4c87-b21b-d1ba6f48b336)

**Comment by Jefferson49** [comment]
Hi, thank you for using SexyPolling!

From your description, I assume that you inserted the plugin code "[sexypolling id="4"]" into the text of an article by editing the article in the backend. It this assumption right?

Which Joomla version and which sexy polling version are you using?

Did you insert the right id? You posted "[sexypolling id="4"]". Therefore, id="4"

You can also insert a plugin by choosing it from the "CMS content" menu. In this case, you can choose from the menu and do not need to handle the code and id by yourself.

![article text menu](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/81484983/251f8a64-376d-4123-9fd9-e1c0d1890450)

Is the plugin activated? Check in System / Plugins:

![plugin](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/81484983/784253f8-50de-454f-9d2d-95399ee0f1ef)

If you want to use SecyPolling without the context of an article, the best way is to create a site module and place it at a certain position etc.:

![create site module](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/81484983/2a1118df-a2da-4f8a-9932-a7714e5cd3e8)

**Comment by mmOrthosoftHM** [comment]
Your assumption is right. I am actually using Quix for editing the sites.
I got it fixed with your help. The plugin was deactivated which i didnt know that i need to activate it. Now everything looks good and its working.
Thank you alot for the help.

Best regards
