### ISSUE TITLE
Various Improvement Suggestions

### ISSUE THREAD

**Issue by Konsider** [Jefferson49/joomla4_plugin_sexy_polling#105]
Just a few suggestions for improvements:

1) It seems the colour associated with a question answer is randomly assigned? It would be good if each question had the option of picking this colour. It would mean that when answers are displayed the user could pick colours that were different enough from each other so that it was more aesthetically pleasing.
Also, the colour assigned to the checkbox tick should match the progress bar in he results. Currently it seems it does not? The proposed answer colour picker should be assigned to both the checkbox and the results progress bar for the answers.

2) It seems right now that the answer selection has a radio button selector and only has a checkbox if multiple answers are enabled. However, it would also be good to this checkbox for single answers as it's more visually striking when something is selected. So, maybe under the general poll options, the user could select different ways of the question being selected. Maybe even more than just those two options.

3) The ability to change the change the order in which the image and answer title are displayed. Currently it is picture first then text, but it's always good to give people as many customisation options as possible.

4) A better way to go "back" to voting. If looking at the results, the only way to go back is to enable the "back" png. However, if this is the only one of the pngs enabled, it doesn't look great and is not immediately clear that this takes a viewer back to the voting. Maybe the option to keep the "vote" button enabled? Or to keep both the vote and view buttons enabled at all times - the just change their "active" state colours based on what is being viewed? Something better than the current back arrow is needed :)
It is of course easy to replace the current back.png but this might be overwritten in a future update and it appears that we have to keep the 30x30 pixel size which isn't great.

5) The ability to change all the English text. For example, "You have already voted..." text or "Allowed count of checked options is..." of mouseover texts like "Back to Answers", etc. Again, it's always good to give people as many customisation options as possible :)

**Comment by Jefferson49** [comment]
Thank you very much for the extensive and well-thought feedback!

Before answering to the detailed questions, I would like to start with explaining my role: I am not the original author of the extension. After the extension was withdrawn from the Joomla extension directory (JED) by the original author and I could not find any suitable free alternative, I decided to fork the code and take over the maintenance. I see my major contribution in migrating the code to Joomla 4 and Joomla 5 and re-introducing the extenstion to the JED. I also worked on bugfixes if requested by users. Regarding the functionality, I only added a very few minor improvements.

**Comment by Konsider** [comment]
Ah, I see :) Well, that's excellent that you decided to do that, as it's a very handy extension. I'm sure a lot of people appreciate your efforts. Don't worry if you can't manage to implement any of my suggestions, or if you decided they are not needed. That's no problem :) Thanks for the great work you've done on it so far!

**Comment by Jefferson49** [comment]
> It seems the colour associated with a question answer is randomly assigned? It would be good if each question had the option of picking this colour. It would mean that when answers are displayed the user could pick colours that were different enough from each other so that it was more aesthetically pleasing.
Also, the colour assigned to the checkbox tick should match the progress bar in he results. Currently it seems it does not? The proposed answer colour picker should be assigned to both the checkbox and the results progress bar for the answers.

Yes, the colors of the answer bars and the colors of the checkboxes are not controlled by the template definitons. Although the original author spent a lot of effort for the overall template customization (which I like), this part was not included. I guess it would add a lot of additonal complexity.

Since focusing on the maintenance, I am afraid it is too huge of a change for my activities. However, if you are capable to work on this, I can support.

**Comment by Jefferson49** [comment]
> The ability to change the change the order in which the image and answer title are displayed. Currently it is picture first then text, but it's always good to give people as many customisation options as possible.

I guess that would need some additonal option "Show name before image (Yes/No)" in the answers menu?

![name_and_image,jpg](https://github.com/user-attachments/assets/bae20948-1e15-4f09-8049-4efdb986e170)

That would be quite feasible to change in the code. However, still needs to change the database definition for answers.

**Comment by Jefferson49** [comment]
> The ability to change all the English text. For example, "You have already voted..." text or "Allowed count of checked options is..." of mouseover texts like "Back to Answers", etc. Again, it's always good to give people as many customisation options as possible :)

That should be possible. You can find the translation files in the following folder:
https://github.com/Jefferson49/Joomla_extension_sexypolling_reloaded/tree/joomla_5.x/com_sexypolling/site/language

"You have already voted..." would be found in this line:
https://github.com/Jefferson49/Joomla_extension_sexypolling_reloaded/blob/joomla_5.x/com_sexypolling/site/language/en-GB/en-GB.com_sexypolling.ini#L15

You can change in the other language files accordingly. 

If you send me the updated language file (e.g. copy it to this issue, or send a pull request), I will add it to the next release.

**Comment by Jefferson49** [comment]
> A better way to go "back" to voting. If looking at the results, the only way to go back is to enable the "back" png. However, if this is the only one of the pngs enabled, it doesn't look great and is not immediately clear that this takes a viewer back to the voting. Maybe the option to keep the "vote" button enabled? Or to keep both the vote and view buttons enabled at all times - the just change their "active" state colours based on what is being viewed? Something better than the current back arrow is needed :)

I agree about the "back to answers" button. Maybe, we could keep a simular looking button like the "vote" and "view" button at the same position even if the results are shown.

**Comment by Jefferson49** [comment]
> It seems right now that the answer selection has a radio button selector and only has a checkbox if multiple answers are enabled. However, it would also be good to this checkbox for single answers as it's more visually striking when something is selected. So, maybe under the general poll options, the user could select different ways of the question being selected. Maybe even more than just those two options.

I found this in the code:
https://github.com/Jefferson49/Joomla_extension_sexypolling_reloaded/blob/joomla_5.x/com_sexypolling/site/helpers/helper.php#L433

Yes, you right: For multiple answers, a checkbox ist shown. For single answers, a radio button is shown.

It would be easy to change this to always use checkboxes. 

With some additional effort (including database change) it would be possible to choose between checkbox and radio button. Either for single votes only, or differnciated between single and multiple answers.

**Comment by Konsider** [comment]
Many thanks for your replies :)

1) That’s disappointing to hear it is too big a job. It would be a nice addition. Unfortunately, I’m not a coder, so I wouldn’t be able to do this.
2) This one is not really that important. It was just something that might’ve been interesting to have. Not a big deal.
3) The language file doesn’t ‘need’ changing. It’s just something that would be handy to allow people to customise if needed. If someone changes the files locally, they would just be overwritten by a future update. So, it would need to have this consideration built in, and would call an external language file that wasn’t updated in future. But again, not really too important a feature if it is too hard to do.
4) Yes, having the vote and back buttons stay is a good plan. But, remember, it might be a good idea to have the active state of each correspond with what is currently being shown :)
5) This is probably only worth doing if you can provide that more complicated way of giving people the option of choosing either. Personally, I prefer the checkboxes, as they give a clearer visual indicator of the answer being selected.

Thanks again for taking the time to go through all the suggestions :)

**Comment by Jefferson49** [comment]
> The language file doesn’t ‘need’ changing. It’s just something that would be handy to allow people to customise if needed. If someone changes the files locally, they would just be overwritten by a future update. So, it would need to have this consideration built in, and would call an external language file that wasn’t updated in future.

I guess what you propose is already included in the Joomla core functionality. You can create **language overrides**. 

![overrides](https://github.com/user-attachments/assets/ac792f47-c89f-4333-89a4-bf44cafd3c23)

**Comment by Konsider** [comment]
Thanks, yep, but not all text is included in the override. But, it's fine :)

Thanks again for all of your comprehensive answers, and best wishes for the future of the plugin! :)

**Comment by Jefferson49** [comment]
I created a new enhancement issue #109 for the "back button". The other ideas and proposal have lower priority or are to difficult to implement. The language issue can be addressed with Joomla overrides.

Thank you for the very good discussion! I appreciate to interact with the users.

**Comment by Jefferson49** [comment]
Today, I published a new version with an additional feature and several bugfixes

**Comment by Konsider** [comment]
> Today, I published a new version with an additional feature and several bugfixes

I just checked it out and it's great! :) Well done, and thanks for all of your hard work!
