### ISSUE TITLE
Translating the names of months impossible

### ISSUE THREAD

**Issue by gcguner** [Jefferson49/joomla4_plugin_sexy_polling#17]
Hi,

I'm interested in translating the frontend part of Sexy Polling to Turkish. As you can see in the screenshots, there is no string for translating the month's names when you debug the language. I searched through the files of the plugin and found the month names in file highstock.js (\com_sexypolling\admin\assets\js\highstock.js) in line 29. But even when I modify this file it affects nothing.

Is there a way to tranlate them, is it an issue or am I missing something?

![SP-1](https://user-images.githubusercontent.com/122140895/211132551-88c2f5c0-0893-4f51-aaee-898b60889970.jpg)
![SP-2](https://user-images.githubusercontent.com/122140895/211132559-d783bbaa-5bcc-4964-93e7-2c8708ecc708.jpg)

**Comment by Jefferson49** [comment]
Thank you for reporting the issue!

A first analysis showed that the dates cannot be translated by translation files. 

The dates shown in the frontend are generated by PHP (seemingly in helper.php and vote. php). It seems that the dates are not localized in the PHP code. Until now, I have never recognized this.

As a first workaround, you might want to use a date format without written letters (only numbers). You can set the date format in the settings for the polls, e.g.: **Date Format = "d.m.Y"**. However, some month data keeps still visible.

I have started to work on improving the code. However, it needs some more time. I will get back to you after some progress.

**Comment by Jefferson49** [comment]
After some struggling, I could find an approach how to translate the dates. I created a beta version with support for the date translation, which is attached as a file and which you can test. 

I could not find out how to translate one of the dates. However, if you use **Date Format = "d.m.Y"** without any "written" monthes, it should be o.k.

It would be nice if you could test and provide some feedback.

[joomla_plugin_sexypolling_reloaded_v4.1.5_beta_date_localization.zip](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/files/10369230/joomla_plugin_sexypolling_reloaded_v4.1.5_beta_date_localization.zip)

**Comment by Jefferson49** [comment]
In the meantime, I found a solution to fix all date translations. Beta version for testing attached.

[joomla_plugin_sexypolling_reloaded_v_4.1.5_beta2.zip](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/files/10403546/joomla_plugin_sexypolling_reloaded_v_4.1.5_beta2.zip)

**Comment by gcguner** [comment]
Hi Jefferson49,

Thank your for your kind support. It shows now the names of the months correctly. I noticed it takes the translation from joomla itself, not using the standalone language file.

**Comment by Jefferson49** [comment]
Happy to hear, that the updated code is working.

Yes, I changed the code to use a specific Joomla Date class, which provides the translation within Joomla already.

**Comment by Jefferson49** [comment]
If it were o.k. for you, it would be nice to contribute your translation files to the project, e.g. attaching it to a Github issue or sending by email: sexypolling.reloaded (at) gmail.com

**Comment by gcguner** [comment]
Here is the Turkish translation of the component. This is only the frontend part because I'm using Joomla backend in English. If nessecery as a linguist gladly I would do the rest of the translation. Thank you for your effort and letting us use this nice extension for free.

[tr-TR.com_sexypolling.zip](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/files/10413844/tr-TR.com_sexypolling.zip)

**Comment by Jefferson49** [comment]
Thank you very much @gcguner for the contribution of the Turkish frontend translation. This will be a very valuable help for further users!

I added the translation file to the code and published it with the new version 4.1.5
