### ISSUE TITLE
Error on running anyfunction

### ISSUE THREAD

**Issue by dedworthdog** [Jefferson49/joomla4_plugin_sexy_polling#26]
Observed with Joomla 4.2.6 and plugin version v4.1.0
An error has occurred.
0 version_compare(): Argument #3 ($operator) must be a valid comparison operator

**Comment by Jefferson49** [comment]
Thank you for reporting the issue!

With the provided information, I can not reproduce the error. Can you provide more information, e.g. the log in the PHP error log file or the complete call stack, which is usually shown after the error message?

What did you do immediately before the error occured?

The version **4.1.0** is outdated. You should install the **latest version 4.1.5** of the plugin. You should be able to find the latest version with the Joomla update management system and install it from there.

With an internet search, I could find the error message twice. In both of these cases, the error was related to the plugin "**edsanimate**", which is not running with PHP8. Could you check for this plugin in your Joomla installation?
https://forum.joomla.org/download/file.php?id=134081&mode=view
https://forum.joomla.de/thread/17072-php7-4-auf-8-1-zeigt-fehler-0-version-compare-argument-3-operator-must-be-a-vali/

**Comment by dedworthdog** [comment]
Hi 
My site is running on PHP 8.1
the plug in edsanimate is not present
And I have version 4.1.5
However, I have dropped back to PHP8 and the sexy polling is now working fine

**Comment by dedworthdog** [comment]
Hi 
My site is running on PHP 8.2
the plug in edsanimate is not present
And I have version 4.1.5
However, I have dropped back to PHP8 and the sexy polling is now working fine

**Comment by Jefferson49** [comment]
Thank you for the additional information. 

I can reproduce the error now, if switching to PHP 8.1. I have no environment available to test PHP 8.2; but should be the same issue.

Reproduced with version 4.1.5, Joomla 3.10.11, PHP 8.1.13 after opening a sexy polling page in the backend.

**Error message:**
0 version_compare(): Argument #3 ($operator) must be a valid comparison operator
/www/htdocs/v134494/administrator/components/com_sexypolling/sexypolling.php:26

**Call stack:**
	Function	Location
1	()	JROOT/administrator/components/com_sexypolling/sexypolling.php:26
2	version_compare()	JROOT/administrator/components/com_sexypolling/sexypolling.php:26
3	require_once()	JROOT/libraries/src/Component/ComponentHelper.php:402
4	Joomla\CMS\Component\ComponentHelper::executeComponent()	JROOT/libraries/src/Component/ComponentHelper.php:377
5	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/AdministratorApplication.php:101
6	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT/libraries/src/Application/AdministratorApplication.php:159
7	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:225
8	Joomla\CMS\Application\CMSApplication->execute()	JROOT/administrator/index.php:51

**Comment by Jefferson49** [comment]
Since PHP 8.1 is more strict on the version_compare function, it created an error. With the commited adaptions in the code, it now runs fine with PHP 8.1; hopefully also on 8.2. 

The bugfix will be included in the next release, which is planned in the next days.

**Comment by Jefferson49** [comment]
Bugfix included in newly released version 4.1.6
