### ISSUE TITLE
version_compare(): Argument #3 ($operator) must be a valid comparison operator

### ISSUE THREAD

**Issue by HDInfautre** [Jefferson49/joomla4_plugin_sexy_polling#28]
Hello
thank you for your extension which seems interesting to me
I have just installed your extension under joomla 4.2.6 / php 8.1.3
I have this error message. 

I'm interested in the fact that any member can launch a poll, even a simple one like https://framadate.org/
Is this possible?
Regards

**Comment by Jefferson49** [comment]
Thank you for reporting the issue!

This issue only occures with PHP 8.1 or 8.2. and has already been fixed some days ago. I will release a new version with the bugfix in the next days.

**Comment by Jefferson49** [comment]
As far as I know, it is not possible to launch a poll by any member. However, you can allow users to add new answers to an existing poll.

**Comment by Jefferson49** [comment]
Same issue like #26, which has already been fixed with https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/commit/212903ce6251ccc5c1b3d029bacc2a2830cf5963

**Comment by Jefferson49** [comment]
Bugfix included in newly released version 4.1.6
