### ISSUE TITLE
nl_NL frontend translation

### ISSUE THREAD

**Issue by crillaerts** [Jefferson49/joomla4_plugin_sexy_polling#32]
[nl-NL.com_sexypolling.zip](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/files/10755247/nl-NL.com_sexypolling.zip)

Hi PFA my translation in Dutch nl_NL for frontend purposes.

**Comment by Jefferson49** [comment]
Thank you very much for the translation! This will help to make the plugin valuable for more users. It will be available with the next release.
