### ISSUE TITLE
0 Class "IntlTimeZone" not found 

### ISSUE THREAD

**Issue by svetgeorgiev** [Jefferson49/joomla4_plugin_sexy_polling#34]
Hey guys, it seems that I have an ussie with the plugin when enabled gives me an error on every frontend page: 

`0 Class "IntlTimeZone" not found. `

I suspect this is an issue with the PHP version, I currently use PHP8
Can someone help, please?

**Comment by Jefferson49** [comment]
Hi Svetoslav,

this is probably the same issue like #30

The IntlTimeZone class is usually included in your PHP installation. IntlTimeZone is part of the PHP "intl" extension. 

Can you check your php.ini file, if the "intl" extension is activated. Your php.ini file must contain the following line:
extension=intl

**Comment by svetgeorgiev** [comment]
Yep, that was the problem. Thank You so much Jefferson49!
