### ISSUE TITLE
Class "IntlTimeZone" not found

### ISSUE THREAD

**Issue by rinenweb** [Jefferson49/joomla4_plugin_sexy_polling#35]
When publishing the module in any page, I get the error "Class "IntlTimeZone" not found".
Using sexypolling_reloaded_v4.1.6 in Joomla 3.10.11.

**Comment by Jefferson49** [comment]
This is probably the same issue like #30, #34

The IntlTimeZone class is usually included in your PHP installation. IntlTimeZone is part of the PHP "intl" extension.

Can you check your php.ini file, if the "intl" extension is activated. Your php.ini file must contain the following line:
extension=intl

**Comment by rinenweb** [comment]
Didn't check those due to seemingly unrelated issue titles. Thank you, enabling PHP "intl" extension solves the issue.
