### ISSUE TITLE
Insert votes not working

### ISSUE THREAD

**Issue by thodorisgo** [Jefferson49/joomla4_plugin_sexy_polling#37]
Hello, 
the function insert votes doesn't work for me when i fill a number and press save i get this error:

**An error has occurred.
1364 Field 'country' doesn't have a default value**

Im on the latest J4 version
Regards

**Comment by Jefferson49** [comment]
Thank you for reporting! I could directly reproduce and fix this issue. Will be available with the next release.

**Comment by WoodyF4u** [comment]
Is this solved yet?
When I add a number in this field and save, I receive this error in Joomla 5:
**1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '08??),(9, '', 2024-03-20 08??),(9, '', 2024-03-20 08??),(9, '', 2024-03-20 08...' at line 1**
