### ISSUE TITLE
Greek language

### ISSUE THREAD

**Issue by thodorisgo** [Jefferson49/joomla4_plugin_sexy_polling#40]
`; com_sexypolling
; Copyright (C) 2010 - 2015 2GLux. All rights reserved.
; License GNU General Public License version 2 or later; see LICENSE.txt, see LICENSE.php
; Note : All ini files need to be saved as UTF-8

COM_SEXYPOLLING_WORD_1="Ψήφοι"
COM_SEXYPOLLING_WORD_2="Σύνολο ψήφων"
COM_SEXYPOLLING_WORD_3="Πρώτη ψήφος"
COM_SEXYPOLLING_WORD_4="Τελευταία ψήφος"
COM_SEXYPOLLING_WORD_5="Προβολή χρονολογίου"
COM_SEXYPOLLING_WORD_6="Απόκρυψη χρονολογίου"
COM_SEXYPOLLING_WORD_7="Ψήφισε"
COM_SEXYPOLLING_WORD_8="Αποτελέσματα"
COM_SEXYPOLLING_WORD_9="Επιλέξτε απάντηση"
COM_SEXYPOLLING_WORD_10="Έχεις ήδη ψηφίσει μια φορά</b>"
COM_SEXYPOLLING_WORD_11="Προσθήκη νέας απάντησης"
COM_SEXYPOLLING_WORD_12="Πρόσθεσε μια απάντηση..."
COM_SEXYPOLLING_WORD_13="Προσθήκη"
COM_SEXYPOLLING_WORD_14="Η απάντησή σου θα εμφανιστεί μετά από έλεγχο"
COM_SEXYPOLLING_WORD_15="Κλίμακας"
COM_SEXYPOLLING_WORD_16="Relative"
COM_SEXYPOLLING_WORD_17="Absolute"
COM_SEXYPOLLING_WORD_18="Ημερομηνία έναρξης δημοσκόπησης "
COM_SEXYPOLLING_WORD_19="Ημερομηνία λήξης δημοσκόπησης "
COM_SEXYPOLLING_WORD_20="Πισω στις απαντήσεις"
COM_SEXYPOLLING_WORD_21="Μπορείς να ψηφίσεις ξανά σε..."
COM_SEXYPOLLING_WORD_22="OK"
COM_SEXYPOLLING_WORD_23="Εναπομένων χρόνος ..."
COM_SEXYPOLLING_WORD_24="Επιτρεπόμενος αριθμός επιλογών είναι"
COM_SEXYPOLLING_WORD_25="Δεν μπορείς να ψηφίσεις!"
COM_SEXYPOLLING_WORD_26="Η ψήφος καταχωρήθηκε"
COM_SEXYPOLLING_POWERED_BY="Powered by"`

**Comment by Jefferson49** [comment]
Thank you very much! This will help further users. I added the translation file to the code and it will be distributed with the next release.
