### ISSUE TITLE
Suggestion export votes

### ISSUE THREAD

**Issue by thodorisgo** [Jefferson49/joomla4_plugin_sexy_polling#45]
Congrats and thanks for the latest version.
I would like to suggest an option to export the votes to csv or xls format for further editing and analyse.
 
Keep up the good work!

**Comment by Jefferson49** [comment]
Thank you very much for the positive feedback!

As an available approach for the export, you could use phpMyAdmin and export the sexy_votes table from the database of your Joomla installation. phpMyAdmin offers an option to export as "**CSV for MS EXCEL**". After downloading the file, you can directly open it as an EXCEL table.

A little bit more advanced approach would be to run a short SQL query in phpMyAdmin to combine some of the sexy polling tables, e.g.: 

`SELECT * FROM jos_sexy_votes INNER JOIN jos_sexy_answers ON jos_sexy_votes.id_answer=jos_sexy_answers.id;`

Afterwards you can export the resulting table with the method like described above.

**Comment by thodorisgo** [comment]
@Jefferson49 probably you don't get notifications for closed issues but i added some updade on an old issue i was facing 
https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/issues/36

**Comment by Jefferson49** [comment]
> probably you don't get notifications for closed issues 

It works that I also get notifications for closed issues. Just had less time and could not give an answer on short term, because I do not understand the behavior.

**Comment by Jefferson49** [comment]
> probably you don't get notifications for closed issues 

It works that I also get notifications for closed issues. Just had less time and could not give an answer on short term, because I do not understand the behavior.

**Comment by Jefferson49** [comment]
Can you work with the proposed approach (phpMyAdmin and CSV EXCEL export)? If yes, I would close the issue.

**Comment by Jefferson49** [comment]
Workaround with phpMyAdmin and CSV EXCEL export can be used, see description above.

**Comment by Jefferson49** [comment]
In the latest [release](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/releases/tag/v5.4.0), a CSV/EXCEL export was implemented.
