### ISSUE TITLE
BLOB 'country' cannot have a default value - BLOB 'country' ne peut avoir de valeur par defaut

### ISSUE THREAD

**Issue by Aucasou** [Jefferson49/joomla4_plugin_sexy_polling#50]
Good morning,

During the installation of Sexy polling reloaded, everything goes well until the display of this message: **BLOB 'country' cannot have a default value**.
The installation is stopped with a message. I couldn't find a table indicating any country.
Thanks for your feedback,
Pascal

Bonjour,

Lors de l'installation de Sexy polling reloaded, tout se passe bien jusqu'à l'affichage de ce message : BLOB 'country' ne peut avoir de valeur par defaut.
L'installation est stoppée avec un message. Je n'ai pas trouvé de table indiquant un quelconque pays.
Merci pour votre retour,
Pascal

**Comment by Jefferson49** [comment]
Thank you for reporting the issue!

In issue https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/issues/46 and https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/issues/49, a similar topic was reported by users with a MySQL data base version before 5.7.24 (or 8.0.13). Can you check your database version?

If possible with your server/provider, you might want to update your MySQL database to a newer version (5.7.24/8.0.13) or later.

If you do not want to update the database, you can install the former v4.1.6 release of the plugin.

**Comment by Aucasou** [comment]
Hello again
Thank-you for your prompt response !
The error occurred on a test site hosted on a **Wampserver 3.3.0** in **PHP 8.0.26** and a **MySQL 8.0.31** database.
I tried the installation on my production site, hosted at OVH, I got the same message.
At OVH, I can't change anything and version 4.1.6 doesn't work better.
I see if the solutions you give work and I come back to you.
Pascal


Rebonjour
Merci pour votre réactivité !
L'erreur s'est produite sur un site d etests héhergé sur un Wampserver 3.3.0 en PHP 8.0.26 et une base MySQL 8.0.31.
J'ai tenté l'installation sur mon site de production, hébergé chez OVH, j'ai le même message.
Chez OVH, je ne peux rien changer et la version 4.1.6 ne fonctionne pas mieux.
Je regarde si les solutions que vous donnez fonctionnent et je reviens vers vous.
Pascal

**Comment by Jefferson49** [comment]
Just recently, I published a new release [v5.0.0](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/releases/tag/v5.0.0), which is avoiding installation errors of the tpye "column 'country' can't have a default value". Maybe, you can check if the new version also solves the issues you described.
