### ISSUE TITLE
List Of surverys category in the same Article

### ISSUE THREAD

**Issue by Gimopa** [Jefferson49/joomla4_plugin_sexy_polling#63]
I'used the release 4.1.7

I associated some of survey at the same category, then I created 1 module of survey with the following configuration:
type survey: surveys
select category: <category>

then I added this module in the article.

the result is:
the template of survey is applied correctly only at first survey
from the second survey an then, nothing template is applied to survey and when the vote is confirmed the animation is not correct

![image](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/94612587/a0a42592-fdb3-4182-975c-eb875185b423)

![image](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/94612587/00fd11af-74a2-42ea-9f4b-57932f00ab94)

**Comment by Jefferson49** [comment]
Hi Gimopa, thank you for reporting the issue!

During testing, I recently identified the same behavior. If more than 1 poll is chosen to be shown in a site module, only the first one has correct CSS and Java Script animation. Other polls, which follow after the first poll, do not work correctly.

I have already fixed this issue with commit 1a66729

You can use the attached beta version, which includes the bugfix. If it works, I will include it in an upcoming release.

[com_sexypolling_v4beta90b027a2.zip](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/files/13196284/com_sexypolling_v4beta90b027a2.zip)

If you have some software development background, you can also patch the changes from commit 1a66729. It is only related to 2 lines of code.

**Comment by Gimopa** [comment]
Great job Jefferson, I changed the two code lines, and it work fine. thanks

**Comment by Jefferson49** [comment]
Same issue like #62. Fixed with https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/commit/1a66729eddedd409e61baffe67c1e92731eb452a
