### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by albinaashevchuk** [Jefferson49/joomla4_plugin_sexy_polling#68]
When install plugin have error on web site --- Class "IntlTimeZone" not found and site dont work

**Comment by Jefferson49** [comment]
Hi Albina, 

the plugin requires the PHP exension "intl" (Internationalization). Usually, the "intl" extension is included in the PHP installation. However, it might be necessary to activate it, i.e. the php.ini file must contain the following line: extension=intl

**Comment by albinaashevchuk** [comment]
Thanks so much!

ср, 8 лист. 2023 р. о 14:32 Jefferson49 ***@***.***> пише:
