### ISSUE TITLE
Number options

### ISSUE THREAD

**Issue by RobertBrachfeld** [Jefferson49/joomla4_plugin_sexy_polling#70]
What doesn't mean:
Number options

**Comment by Jefferson49** [comment]
Hi Robert,

> What doesn't mean: Number options

The maximum number of allowed checked options, which can be chosen in parallel. Use only when multiple ansers is set to yes. Example: If set to 0, there is no limits on checked options count. If 3, users can check only 3 options.

You can get this information, if you move the mouse over the text "Number options"
