### ISSUE TITLE
Max votes per logged in user or IP

### ISSUE THREAD

**Issue by RobertBrachfeld** [Jefferson49/joomla4_plugin_sexy_polling#74]
I puted 100 in "Max votes per logged in user or IP", but still I can make only 1 vote. What is wrong?

**Comment by Jefferson49** [comment]
You can only vote again after the site is reloaded or opened in a new browser window.

This issue is known and more or less the same as issue #67

**Comment by Jefferson49** [comment]
Closed as duplicate to #67
