### ISSUE TITLE
Invalid token and no poll showing 

### ISSUE THREAD

**Issue by steepedincode** [Jefferson49/joomla4_plugin_sexy_polling#75]
We started getting an "invalid token" error when voting, and now all we get is "Sexy Polling: There is nothing to show!" on the front-end via the module and direct use of the shortcode. In addition, all previous votes seem to have been removed. At a loss to explain what suddenly went wrong. 

Joomla 4.4.1
PHP 8.1.26
MySQL 5.7
Sexy Polling Reloaded 5.1.1

Appreciate any tips.

**Comment by Jefferson49** [comment]
Thank you for reporting the issue.

Did this behavior occur after updating from an earlier version (which one?)? Or directly after a fresh install? Did version 5.1.1 work after installation and failed later?

Invalid token is reported as an error if a vote (or add answer request) is received with a wrong session token. This is a mechanism to inhibit access from outside of the authorized session or after a time Limit for the session, which is defined by your server.

"There is nothing to show" could mean that there are no answers available for the poll. Do you see answers in the backend?

**Comment by steepedincode** [comment]
Hi @Jefferson49, 

Thank you so much for the quick reply and attention to this. Here's what I know: 

1) My client wanted to extend the voting period to the end of 2024, so that was changed. 
2) The client then reported the "Invalid Token" while testing the front-end voting (via the Sexy Polling Module). 
3) I got the same result. 
4) All votes WERE there and viewable in the admin until I upgraded from 5.0 (I believe it was) to 5.1.1 -- UPDATE on this: when I filter "Votes" in the Admin to "Select Poll" I see tons of votes, but when filtering to the poll that collected them, all votes disappear. I can't explain it. We've only had one poll and one category for the longest time. 
5) Since these changes, the front-end module simply displays "Nothing to show"; no way to vote or anything. 

My attempts to resolve the issue were to create a new poll, new category, and even a new module, among other steps, but I haven't been able to get past the "Nothing to show" issue so as to test voting again. 

Hope these details give a few more clues. 

Thank you ahead

**Comment by Jefferson49** [comment]
Thank you for describing the issue in more detail.

To analyze the background, it would be very helpful if you could send me the Sexypolling tables from your database. These tables contain all the configuration and poll data from your installation. You can select the 5 tables in phpMyAdmin and export them to a SQL file. The 5 tables are shown in the following screenshot:

![MySQL_tables_sexypolling](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/81484983/bd5ae9a7-1082-4d7b-8bdc-a2d69913ef85)

You can ZIP the SQL file and attach it to this issue. If you do not want to share your data on Github, you can also send the SQL file by email to: sexypolling.reloaded(at)gmail.com

If you have a former backup of your database, you can also try to delete the existing tables and substitute them with the 5 Sexypolling tables from your backup (before the issue occured). That should recover your data. However, **be sure you save/export the current tables before deleting**.

**Comment by steepedincode** [comment]
@Jefferson49, 

Thank you very much for the ongoing support on this. Email on the way to you with a .zip of the database tables, and four screenshots from the admin, plus the site URL. 

Regards

**Comment by steepedincode** [comment]
OK, with your excellent help, we have resolved the issue. Thank you!
