### ISSUE TITLE
Display Issue in Backend of Sexy Polling Reloaded with Joomla 4.4.2

### ISSUE THREAD

**Issue by 4creator** [Jefferson49/joomla4_plugin_sexy_polling#80]
Hello,

I have recently started using Sexy Polling Reloaded with Joomla 4.4.2. Upon accessing various sections of the backend, I noticed that the menu and filters at the top are not displaying correctly. After inspecting the backend's source, I found that the file **administrator/components/com_sexypolling/assets/css/icons_j3.css** is being loaded. 

Currently, I have temporarily added the following source to **icons_j3.css** to circumvent this issue:
```
.com_sexypolling .sidebar-nav .flex-column {flex-direction: unset !important}
.com_sexypolling .sidebar-nav .d-md-block {display: inline-flex !important}
.com_sexypolling .sidebar-nav .d-md-block .chosen-container {max-width: 200px !important; margin-right: 20px}
```
Although this CSS serves as a temporary workaround, it is not ideal. I would appreciate it if you could consider making improvements around the "sidebar-nav" section of the Sexy Polling Reloaded backend.

Regards

**Comment by Jefferson49** [comment]
> I noticed that the menu and filters at the top are not displaying correctly

I am not sure if I understand your issue correctly. Can you describe in more detail or post a screenshot?

For me, the backend for  Sexypolling looks like the screenshot below. I have only been testing with the default "**Atum**" administrator template. Which template do you use?

![Screenshot Sexypolling backend](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/81484983/7f690721-e4da-4f3b-a163-c0ec283d720c)

**Comment by 4creator** [comment]
I apologize if my explanation was not clear enough. The screenshot you provided is from the "Overview" page, which does not have the issue I mentioned. My concern pertains to the headers of other pages like "Polls" and "Answers." Please refer to the attached screenshot for clarification. Also, I am using the Atum template as well.

BEFORE:
![before](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/157468187/763c719e-dfcf-440a-b936-4b3fac27fda7)

AFTER:
![after](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/157468187/8bc2ea6c-7d01-4794-8afc-777c92b0db5d)

**Comment by 4creator** [comment]
For your reference, I have created a mock-up of a Joomla 4 style header using headers from _other extension_. The icons attached to the menu are provisional, and I believe more suitable icons could probably be selected.

![mock-up](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/157468187/392126e8-20a0-4479-a90d-4dfab2b7fa29)

**Comment by Jefferson49** [comment]
Thanks for the proposal, which looks very interesting. Would it be possible to send me your current code? Or send a link to the code of the other extension, which you mentioned.

Maybe, you can add the changed files to a zip file and attach it here. Or you can send it by email to sexypolling.reloaded(at)gmail.com. Or create a fork and send a pull request.

**Comment by 4creator** [comment]
The attached mock-up is a pseudo-creation I made by modifying the text in Safari's Web Inspector. Thus, unfortunately, the code does not exist.
The original is based on Membership Pro's category management.

![membership](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/157468187/a9f316b5-eb0d-435a-832c-9e9327ec3e73)

Attached is the HTML of the category management (header section) of Membership Pro, just in case. I have no knowledge or experience with PHP.
[membership.txt](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/files/14077748/membership.txt)

**Comment by Jefferson49** [comment]
> Attached is the HTML of the category management (header section) of Membership Pro, just in case. I have no knowledge or experience with PHP.

It seems that the HTML of this component has more or less the same structure like Sexy Polling: It creates a `<ul>` list and contains the links in the `<li>` elements.

Checking the code of Sexy Polling showed that it uses a library class of the Joomla CMS to render this view. Therefore, no Sexy Polling code.

The summary for me is that the view can only be modified by CSS.

**Comment by Jefferson49** [comment]
Based on your proposal - maybe, something like this:

![CSS menu](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/81484983/333e8549-167a-4c2b-849b-278165ee6a3e)

.sidebar-nav .flex-column {
	flex-direction: row !important;
}
.sidebar-nav .d-md-block {display: inline-block !important}
.sidebar-nav .d-md-block .chosen-container {max-width: 200px !important; margin-right: 20px}

.sidebar-nav li.item:hover, .sidebar-nav li.active {
    border-radius: 3px;
}

.sidebar-nav li a {
	border: solid grey;
	width: 100px;
	margin: 5px;
	border-radius: 3px;
}
