### ISSUE TITLE
My feedback: Points for Improvement

### ISSUE THREAD

**Issue by 4creator** [Jefferson49/joomla4_plugin_sexy_polling#81]
Hello Jefferson49,

I would like to express my sincere gratitude for your contribution that has made Sexy Polling available for Joomla 4. As a user, I wish to provide some feedback that might help in further developing Sexy Polling into Sexy Polling Reloaded.

### Global Configuration
It appears that the current Sexy Polling Reloaded lacks Global Configuration (options). Our website has multiple administrators, making the permissions settings within the Global Configuration crucial. In particular, settings such as '**Configure ACL & Options**' and '**Access Administration Interface**' are essential for managing multiple administrators effectively. Without these options, it becomes challenging to use Joomla with multiple administrators.

### Answer: [ Edit ]
In the '**Answer: [ Edit ]**' section of Sexy Polling Reloaded, the '**Name**' input field should allow HTML usage, as demonstrated in the included demo. However, upon saving, any HTML content in the '**Name**' field is stripped out, resulting in it being saved as plain text. Consequently, I had to manually modify the **name** column in the **#__sexy_answers** table via phpMyAdmin to enable HTML. I kindly request improvements to retain HTML in the '**Name**' field after saving.

These are my feedback points at this time. I hope this feedback will be useful for the future development of Sexy Polling Reloaded.

Regards

**Comment by Jefferson49** [comment]
> In the 'Answer: [ Edit ]' section of Sexy Polling Reloaded, the 'Name' input field should allow HTML usage, as demonstrated in the included demo

Yes, this is a planned feature and seemingly worked in earlier versions of the original Sexypolling extenstion. Some time ago, I have already created an issue for that => #33 

I will try to check what is the reason for that.

**Comment by Jefferson49** [comment]
> It appears that the current Sexy Polling Reloaded lacks Global Configuration (options).

I guess you are refering to extension options like in the following screenshot.

![extensions settings](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/81484983/f8dc8057-a54b-4a0c-947f-e5076d4aadce)

At the moment, I do not have experiences with global configuration. Maybe, I can check some other extensions how they manage it.

> Configure ACL & Options

I guess you are refering to "Security Options => Check Access Control", which can be currently configured for each of the polls. Is that correct?

> Access Administration Interface

Can you explain in more detail?

**Comment by Jefferson49** [comment]
> It appears that the current Sexy Polling Reloaded lacks Global Configuration (options).

I managed to integrate global configuration options, see screenshot. Does this meet your requirements? Is it alredy enough to integrate that and Joomla will handle the related access rights? Or do I have to react to this settings in the component code?

![sexypolling_access](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/81484983/d0427518-72a8-48c0-b0f9-1b0889287024)

**Comment by 4creator** [comment]
>  I have already created an issue for that => #33

I had missed it, sorry.

>  I managed to integrate global configuration options, see screenshot. Does this meet your requirements?

Yes, this is exactly the initial Global Configuration I was looking for. I would be very happy if this Global Configuration is implemented!

**Comment by 4creator** [comment]
For now, I found out that access control (permissions) to the Sexy Polling admin panel can be controlled using the **rules** column of the **#__assets table**, so I set it directly in phpMyAdmin. 😄

Under my environment, the following settings were used:
`{"core.admin":{"14":0},"core.manage":{"14":0,"16":0,"15":0,"17":0}}`

**Comment by Jefferson49** [comment]
> Yes, this is exactly the initial Global Configuration I was looking for. I would be very happy if this Global Configuration is implemented!

After further testing, this seems to work. The attached zip file contains the component version v5.1.2 plus the configuration feature. Maybe, you have the chance to test it. I plan to add it to the next release (not planned yet).

[com_sexypolling_v5.1.2_f62f2550.zip](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/files/14102666/com_sexypolling_v5.1.2_f62f2550.zip)

**Comment by Jefferson49** [comment]
> In the 'Answer: [ Edit ]' section of Sexy Polling Reloaded, the 'Name' input field should allow HTML usage, as demonstrated in the included demo. However, upon saving, any HTML content in the 'Name' field is stripped out, resulting in it being saved as plain text. 

I was able to fix #33, which also solves your issue about HTML code in the 'Name' input field. I will include the bugfix in the next release.

**Comment by 4creator** [comment]
Thank you for providing the pre-release version of com_sexypolling_v5.1.2. I will test it and send you feedback as soon as possible.

**Comment by 4creator** [comment]
I am writing this because I was a little curious.
I get the following message right after installing Sexy Polling Reloaded. Shouldn't it say **extension** or **component** instead of plugin (kinda like WordPress)?

> Sexy Polling Reloaded - A **plugin** for polling with single/multiple voting, adding answers by users, start/end dates, voting periods, and extensive template customizing.

**Comment by 4creator** [comment]
I have installed and checked the pre-release version v5.1.2 that you provided.

When I tested changing and saving some parameters in the **Sexy Polling Configuration**, I was able to confirm that as expected, the values in the **rules** column of the **#__assets table** were changed.

However, it seems there is no **Option** button to access the Sexy Polling Configuration.

My understanding is that normally, as per the extension specifications, there should be an **Option** button in the top right of the page (The screenshot below shows mockup of where the button should be).

![option](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/assets/157468187/fa1a1b14-b289-4a42-951b-ecb667295ac4)

**Comment by Jefferson49** [comment]
> Shouldn't it say extension or component instead of plugin (kinda like WordPress)?

Yes, I agree. Indeed, this is kind of a legacy of the former Sexy Polling extension, because it used to call itself a "plugin" instead of an extension; indeed, it is a component + plugin + module. In some parts of the code and translation, the legacy "plugin" is still visible.

I will change the mentioned message.

**Comment by Jefferson49** [comment]
> My understanding is that normally, as per the extension specifications, there should be an Option button in the top right of the page

Yes, I agree. I will try to add a button; at least on the "overview" page.

**Comment by 4creator** [comment]
> I was able to fix #33, which also solves your issue about HTML code in the 'Name' input field. I will include the bugfix in the next release.

I have confirmed that this issue has been resolved. Thank you very much. (^_^)/*

**Comment by Jefferson49** [comment]
All sub issues solved
