### ISSUE TITLE
Issue with "Show Results During Poll" to "no”

### ISSUE THREAD

**Issue by gnutello** [Jefferson49/joomla4_plugin_sexy_polling#90]
Hi Jefferson 
I’m managing a poll on a Joomla 3.10.12 site with 5.0.4.0 sexy polling.
I having an issue when I set "Show Results During Poll" to "no”, the Results remain visible.
I need that the results must be hidden.
I saw that in 5.0.4.0 release you worked to solve an issue just on that option. May this have caused the new issue that I’m experiencing?
Many thanks for your attention.

**Comment by Jefferson49** [comment]
Thank you very much for reporting the issue. 

Yes, I introduced an error with the bugfix of #85.

Please note that I identifyed an other bug #91 while fixing this issue, which also allows to view the poll results.

**Comment by Jefferson49** [comment]
As a workaround you can have a look at the bugfix in 62d6b06 and patch the file components/com_sexypolling/site/helpers/helper.php

You only need to substitue "===" by "=="

I will probably release a new version in the next week.

**Comment by gnutello** [comment]
Thank you very much, I patched and it works fine now!
I also encountered a second issue: when I set the calendar for a certain day I found the start delayed by an hour compared to the scheduled time (00:00). My local time is Rome +1 and even by changing the joomla global configuration to London the issue persists.
Please take a look at this video: https://youtu.be/tS6lYRTtblA

**Comment by Jefferson49** [comment]
> I also encountered a second issue: when I set the calendar for a certain day I found the start delayed by an hour compared to the scheduled time (00:00). My local time is Rome +1 and even by changing the joomla global configuration to London the issue persists.

Yes, I can reproduce this. I created a separate issue #93.
Potential root cause: JavaScript for warning message does not use timezone for date calcluation; instead uses UTC.
