### ISSUE TITLE
SQL error when adding count to field Insert votes in Answers

### ISSUE THREAD

**Issue by WoodyF4u** [Jefferson49/joomla4_plugin_sexy_polling#98]
Hi,
If I go to Answers and then enter a certain value in the Insert Votes field and choose Save, I get this error message:

_An error has occurred.

    1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '21??),(6, '', 2024-03-25 21??),(6, '', 2024-03-25 21??)' at line 1_ 

I work with Joomla 5.
Does anyone know how I can solve this?

I also cannot find the field in the SPR tables in the database.
So filling it in manually was not possible either.

Regards,
Wouter

**Comment by Jefferson49** [comment]
Hi Wouter,

thank you for reporting the issue! Sorry, I did not react on your post in #37, because there was something going wrong with the email notification system and I did not get an email.

> If I go to Answers and then enter a certain value in the Insert Votes field and choose Save, I get this error message:

Yes, I can reproduce the error and also get a PHP error message. I will check the code in the next days.

**Comment by Jefferson49** [comment]
I found the bug and fixed it in the code. I will publish a bugfix release in the next days.

**Comment by Jefferson49** [comment]
I have just published a bugfix release [v5.5.1](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/releases/tag/v5.5.1), which fixes the issue.
